### ISSUE TITLE
Error when downloading from YouTube

### ISSUE THREAD

**Issue by dejan995** [piyx/YoutubeSpotifyDL#7]
I recieve the following error when trying to download [this](https://www.youtube.com/watch?v=PEKkdIT8JPM) song from Youtube.
I think that the Korean letteres in the title are confusing the script or the script is not programmed to handle them.

```shell
? Download From?  2.Youtube
? What do you want to do?  2.Download a particular song
? Enter artist name:  Dreamcatcher
? Enter song name:  Because
? Where do you want to download the song?  3.Enter a custom download path
? Enter path where songs should be downloaded:  /downloads
Press ctrl+c to stop.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app/downloader.py", line 36, in download
    song_name = re.sub(INVALID, "", f'{song.artist} {song.title}') # Remove invalid chars
AttributeError: 'NoneType' object has no attribute 'artist'
```

**UPDATE:**
Just saw this:
```python
    INVALID = r"[#<%>&\*\{\?\}/\\$+!`'\|\"=@\.\[\]:]*"
    song_name = re.sub(INVALID, "", f'{song.artist} {song.title}') # Remove invalid chars
```
The song in question has invalid characters in the title.
Is there a chance these types of song titles will be able to download in the future or is that invalid variable here to stay?

**Comment by piyx** [comment]
The issue has been fixed!
